module.exports = {
	"siteName" : "Multi Level Signals",
	"host" : "http://localhost:3090",
	"port" : 3090,
	"staticPath" : "public",
	"staticMaxAge" : 0,
	"urlencoded.limit" : "1mb",
	"jsonencoded.limit" : "1mb",
	"logPath" : "logs",
	"logFile" : "logs.log",
	"mongodb.databaseUrl"  : "mongodb://127.0.0.1:27017/signals",
	"mongodb.databaseName" : "signals",
	"auth.google.clientID"     : "351821993130-srh5d10cn3kfchnmskkbqoja6q8voidv.apps.googleusercontent.com",
	"auth.google.clientSecret" : "YFkVpNR-d8gVF2dttYP3ZqZ9",
	"auth.google.callbackURL"  : "/auth/google/return",
	"auth.google.successRedirect" : "/auth/oauth-success",
	"auth.facebook.clientID"     : "1555966744693412",
	"auth.facebook.clientSecret" : "7b90e6d1a61990cd1daee35c108f0b00",
	"auth.facebook.callbackURL"  : "/auth/facebook/return",
	"auth.facebook.successRedirect" : "/auth/oauth-success",
	"auth.signOutRedirect" : "/",
	"session.secret" : "1FRlUu7Jledo1JOp6otFhCIFddUHEY2m",
	"session.maxAge" : 604800000,
	"session.name" : "signals"
}